### PR TITLE
Create Profile, Login and get Profile endpoints

### PR DESCRIPTION
**Pull request by daviddiefenderfer**
Adding CRUD functionality to Profiles and adds Login route

Per issues:
#9 #5

### CODE REVIEW

**Comment by jbowden1982** [comment]
Hey ci is failing due to node gyp.  What version of node are you on. We are using 7.1.  Check your version and delete node_modules see if u get the same node_gyp error.

**Comment by daviddiefenderfer** [comment]
Oh, I'm 6.4. I'll upgrade real quick

**Comment by daviddiefenderfer** [comment]
Looks like it might be us needing to set the compiler env?
https://github.com/travis-ci/travis-ci/issues/4771

**Comment by daviddiefenderfer** [comment]
@jbowden1982 looks like that fixed it!

**Comment by jbowden1982** [comment]
Nice looks like that did it...

**Comment by jbowden1982** [comment]
👍  Merge it

**Comment by thiyagaraj** [comment]
@daviddiefenderfer Is that a test jwt key, if not, Travis can encrypt/decrypt it for you, the encrypted copy can be in git to avoid public exposure

**Comment by daviddiefenderfer** [comment]
@thiyagaraj Yes it is for testing at the moment, I'll write up an issue to handle the jwt key properly

**Comment by thiyagaraj** [comment]
Thank you!

**Pull request merged**
